services:
  qis-note-notifier:
    build: .
    container_name: qis-note-notifier
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data:/data
