services:
  qis-note-notifier:
    build: .
    container_name: qis-note-notifier
    restart: unless-stopped
    environment:
      - QIS_USERNAME=${QIS_USERNAME}
      - QIS_PASSWORD=${QIS_PASSWORD}
      - TZ=Europe/Berlin
    volumes:
      - ./data:/data
